name: 'Amplify PR Preview'

on:
  pull_request:
    types:
      - opened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ACCOUNT_ID: ${{ inputs.ACCOUNT_ID || (github.ref == 'refs/heads/main' && github.event_name == 'push') && 242295598087 || 778447792808 }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_REGION: 'us-west-2'

jobs:
  amplify-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set env variables
      id: setEnvName
      run: |
        echo "##[set-output name=branchName;]$(echo ${GITHUB_HEAD_REF})"

    - name: configure aws CI Cache credentials
      id: ci-creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: 'us-west-2'
        role-to-assume: arn:aws:iam::083632199359:role/gha_oidc_bonsai_amplify_access
        output-credentials: true

    - name: Deploy PR Preview (Reports)
      uses: ./.github/actions/amplify
      with:
        branch_name: ${{ steps.setEnvName.outputs.branchName }}
        amplify_command: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ steps.ci-creds.outputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ steps.ci-creds.outputs.aws-secret-access-key }}
        AWS_SESSION_TOKEN: ${{ steps.ci-creds.outputs.aws-session-token }}"
        # EnvironmentVariables: ''
        AmplifyAppName: Reports # just a string to identify which app is deploying, can be anything
        AmplifyAppId: d1ra426pwarsme # TODO: Change this once morgan is done -- see https://us-west-2.console.aws.amazon.com/amplify/home?region=us-west-2#/d1ra426pwarsme
